### ISSUE TITLE
Gradle Version 1.10 is Required?

### ISSUE THREAD

**Issue by stephen-t-dodds** [flyver/Flyver-SDK#1]
I downloaded the SDK and ran it as a gradle project, but i get the error that gradle version 1.10 is needed so I need to change gradle wrapper (currently it is gradle-2.2.1). 

When I change it to 1.10, I get a never ending web of bugs that I fix and another comes.

Any suggestions?

Thanks,

Stephen

p.s. sweet project and awesome mentality - I ordered the dev kit and I am hoping to get this thing running so I can hack up some apps some time soon

**Comment by stephen-t-dodds** [comment]
If I change the classpath in the master build.gradle to a higher version to match my android studio version: classpath 'com.android.tools.build:gradle:1.0.0'

The error above goes away, but Error:(33, 0) Project with path ':utils' could not be found in project ':FlyverCore'. comes next.

If I fix that, I get more path errors. Just so you have some insight as to what I have tested so far.

**Comment by tnedev** [comment]
Hi Stephen, 

Thank you very much for your interest and appreciation for the project. 

Are you trying to build the SDK modules from this repository?
If yes, we could recommend that you try to build the Flyver Test App first. It contains all the components from the SDK and it will be a lot easier than connecting the dots together: https://github.com/flyver/Flyver-Apps/tree/master/FlyverTest

The SDK repo hasn't been updated soon and the Android Studio changed versions since. We will check and update to fix the build issues. 

If the error comes from an app you were trying to build, let me know. 

Hope you will find it interesting and exciting. An update on the wiki pages is coming soon and some new opportunities along.

**Comment by stephen-t-dodds** [comment]
Well done! Works perfect! Thanks for the quick response!

Yeah, went for the SDK first, but working from this starter app is
definitely the best way to start anyway.

Thanks again! Our Kit should come in in the next few weeks so I will keep
you updated on our progress!

Stephen

**Comment by tnedev** [comment]
Great! I'm glad to hear that the build went without any problems. 
We will fix the SDK components issue too. 
Where are you from?

**Comment by stephen-t-dodds** [comment]
I am in the Valley\* (silicon valley) - Palo Alto, CA (US). I am originally
from Nebraska (US).

**Comment by tnedev** [comment]
Don't hesitate to keep us updated with what your are building and any issues you are having.

**Comment by stephen-t-dodds** [comment]
Okay great, thank you. Also, are we able to make non GPL apps?

Are you from Bulgaria?

Stephen

**Comment by tnedev** [comment]
The GPL license is for derivative work from the SDK. You can't clone the repository and start a new open source project without following the GPL. You can, however, build closed and commercial applications based on the SDK. 
At some point this will be cleared with appropriate license. But as a co-founder you could take my word for it for now :) 
This will also change when we release the marketplace for publishing and monetizing applications. 

We are currently based in Bulgaria. 

Tihomir

**Comment by stephen-t-dodds** [comment]
Awesome! Thanks!!

Bulgaria looks pretty cool - have not been there though. What made you guys
decide to go with that location?

Stephen

**Comment by tnedev** [comment]
We are from here and it has a great environment for software development. Many talented young developers at very reasonable cost. Also good emerging startup environment. The drawback is that is way less connected than the Valley and therefore harder to get noticed.

**Comment by stephen-t-dodds** [comment]
Ahhh, that sounds pretty cool, but I understand where you are coming from
on the drawback.

If this things works as well as I think it will, I think you guys will be
set.

**Comment by tnedev** [comment]
Hi Stephen, 

Let me know if you have received the kit and for any problems you are having. 
We also have a forum if you have a topic for discussion: http://flyver.co/forum/
